### ISSUE TITLE
Consider publishing to npm

### ISSUE THREAD

**Issue by wagich** [dominikbulaj/WaypointsTypings#1]
Now that there is some official guidance (and a bit less of a mess) for publishing typings, it'd be very nice if you published the type definitions under @types/waypoints so that they can be consumed easily.

In any case: thank you very much for creating the definitions in the first place!

**Comment by Koloto** [comment]
@dominikbulaj May I use your .d.ts to create PR to https://github.com/DefinitelyTyped/DefinitelyTyped? After merging your typing will be published as a public npm package `@types/waypoints`.

**Comment by dominikbulaj** [comment]
Hi, @Koloto  yes sure! Thanks!

Sorry, @wagich I had no time to take care of it :(

**Comment by wagich** [comment]
@dominikbulaj No need to apologize! :)

**Comment by Koloto** [comment]
@dominikbulaj PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17997 - merged
Thanks for your work!

**Comment by Koloto** [comment]
@dominikbulaj, @wagich I think this issue can be closed. And thanks again:)

@dominikbulaj It will be great if you refer to DefinitelyTyped in `readme.md`.

**Comment by dominikbulaj** [comment]
@Koloto Thank you! Added [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) note. Closing issue.
